### ISSUE TITLE
Disable AdminFilter

### ISSUE THREAD

**Issue by dev4java11** [adminfaces/admin-showcase#14]
Hello, I has a problem with Admin Filter (com.github.adminfaces.template.session.Admin Filter ) because the atributes adminConfig and adminSession does not injected right. Please can you validate if these atributes are nulls and automatically set disableFilter in true. I use Spring Boot and JSF.

I show you the exception that I have gotten:

java.lang.NullPointerException: null
	at com.github.adminfaces.template.session.AdminFilter.init(AdminFilter.java:48) ~[admin-template-1.0.0-RC9.jar:na]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285) ~[catalina.jar:8.5.16]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266) ~[catalina.jar:8.5.16]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108) ~[catalina.jar:8.5.16]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590) [catalina.jar:8.5.16]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233) [catalina.jar:8.5.16]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.16]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [catalina.jar:8.5.16]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [catalina.jar:8.5.16]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by rmpestano** [comment]
Hi @hernxntk,

SpringBoot is not supported yet, however take a look at this issue because a user has made some progress:
https://github.com/adminfaces/admin-template/issues/13

**Comment by rmpestano** [comment]
For your specific case you should create a bean to hold admin config:

````
@Bean
	public AdminConfig adminConfig() {
		return new AdminConfig();
	}

````
