### ISSUE TITLE
Don't work in Tomcat 8

### ISSUE THREAD

**Issue by ChristianRoig** [adminfaces/admin-showcase#16]
In Tomcat 8 have this error:

17-Jan-2018 18:16:58.065 SEVERE [http-nio-8084-exec-200] null.null Critical error during deployment: 
 java.lang.NoClassDefFoundError: Could not initialize class org.omnifaces.config.BeanManager
	at org.omnifaces.application.OmniApplication.<init>(OmniApplication.java:69)
	at org.omnifaces.application.OmniApplicationFactory.createOmniApplication(OmniApplicationFactory.java:89)
	at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:54)
	at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93)
	at com.sun.faces.config.InitFacesContext.getApplication(InitFacesContext.java:144)

and versions of showcase and starter in Tomcat no work too (in my environment).
additional config is need?

Te pregunto en español que es mas cercano al portugués. 
No me anda en Tomcat, existen instrucciones de uso especiales para Tomcat?
Solo pude hacer andar el showcase en Glassfish, uso Netbeans para desarrollar.

**Comment by rmpestano** [comment]
hola, hay un escaparate (no tan actualizado) para Tomcat, ¿lo has probado? aquí está el camino: https://github.com/adminfaces/admin-showcase-tomcat
 
(translated via Google Translator)

**Comment by rmpestano** [comment]
Whats the error you get in starter-tomcat?

Also there is a vídeo here: https://youtu.be/SKMkh1MR1cg
