### ISSUE TITLE
Try start with swarm but dont working

### ISSUE THREAD

**Issue by jandrei** [adminfaces/admin-showcase#23]
I am using apache-maven-3.5.4

mvn wildfly-swarm:run -Pswarm
....
[INFO] 
[INFO] ----------------< com.github.adminfaces:admin-showcase >----------------
[INFO] Building admin-showcase 1.0.0-RC18
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
.
[INFO] Starting .war
Thu Aug 16 00:54:30 BRT 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
2018-08-16 00:54:30,982 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2017.5.0
2018-08-16 00:54:30,991 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      JCA - STABLE          org.wildfly.swarm:jca:2017.5.0
2018-08-16 00:54:30,991 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:2017.5.0
2018-08-16 00:54:30,992 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:        CDI Configuration - STABLE          org.wildfly.swarm:cdi-config:2017.5.0
2018-08-16 00:54:30,994 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:2017.5.0
2018-08-16 00:54:30,995 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      EJB - STABLE          org.wildfly.swarm:ejb:2017.5.0
2018-08-16 00:54:30,995 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:2017.5.0
2018-08-16 00:54:30,996 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2017.5.0
2018-08-16 00:54:30,996 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      JSF - STABLE          org.wildfly.swarm:jsf:2017.5.0
2018-08-16 00:54:33,914 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
2018-08-16 00:54:34,033 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: WildFly Swarm 2017.5.0 (WildFly Core 2.2.1.Final) starting
2018-08-16 00:54:34,123 INFO  [org.wildfly.swarm] (MSC service thread 1-8) WFSWARM0019: Install MSC service for command line args: []
2018-08-16 00:54:35,124 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([]): java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.ejb3
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1322)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:468)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349)
	at org.jboss.as.server.ServerService.boot(ServerService.java:397)
	at org.jboss.as.server.ServerService.boot(ServerService.java:366)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/metadata/ejb/main/module.xml
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
	... 11 more
Caused by: java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/metadata/ejb/main/module.xml
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:85)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:439)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:342)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:289)
	at org.jboss.modules.Module.addPaths(Module.java:1079)
	at org.jboss.modules.Module.link(Module.java:1449)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1477)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:225)
	at org.jboss.modules.Module.loadServiceFromCallerModuleLoader(Module.java:406)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:120)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/jboss/metadata/ejb/main/module.xml
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:228)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:61)
	... 17 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to add artifact 'org.jboss.metadata:jboss-metadata-ejb:10.0.0.Final' (position: END_TAG seen ...tifact name="org.jboss.metadata:jboss-metadata-ejb:10.0.0.Final"/>... @7:74) caused by: java.util.zip.ZipException: error in opening zip file
	at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:836)
	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:739)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:535)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:340)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:226)
	... 18 more

2018-08-16 00:54:35,167 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
2018-08-16 00:54:35,205 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
2018-08-16 00:54:35,205 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-08-16 00:54:35,205 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-08-16 00:54:35,206 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-08-16 00:54:35,206 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:498)
2018-08-16 00:54:35,206 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:39)
2018-08-16 00:54:35,206 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.main(MainInvoker.java:70)
2018-08-16 00:54:35,206 ERROR [stderr] (main) Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: Operation failed
2018-08-16 00:54:35,207 ERROR [stderr] (main) 	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:45)
2018-08-16 00:54:35,207 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.bootstrap(ServerBootstrapImpl.java:109)
2018-08-16 00:54:35,207 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.start(Swarm.java:369)
2018-08-16 00:54:35,207 ERROR [stderr] (main) 	at org.wildfly.swarm.Swarm.main(Swarm.java:623)
2018-08-16 00:54:35,207 ERROR [stderr] (main) 	... 6 more
2018-08-16 00:54:35,208 ERROR [stderr] (main) Caused by: java.util.concurrent.ExecutionException: Operation failed
2018-08-16 00:54:35,208 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
2018-08-16 00:54:35,208 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
2018-08-16 00:54:35,208 ERROR [stderr] (main) 	at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:148)
2018-08-16 00:54:35,209 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:202)
2018-08-16 00:54:35,209 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.RuntimeServer$Proxy$_$$_WeldClientProxy.start(Unknown Source)
2018-08-16 00:54:35,209 ERROR [stderr] (main) 	at org.wildfly.swarm.container.runtime.ServerBootstrapImpl.lambda$bootstrap$1(ServerBootstrapImpl.java:152)
2018-08-16 00:54:35,209 ERROR [stderr] (main) 	at org.wildfly.swarm.spi.api.ClassLoading.withTCCL(ClassLoading.java:43)
2018-08-16 00:54:35,214 ERROR [stderr] (main) 	... 9 more
2018-08-16 00:54:35,269 ERROR [stderr] (main) Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
2018-08-16 00:54:35,269 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
2018-08-16 00:54:35,269 ERROR [stderr] (main) 	at org.jboss.as.server.ServerService.boot(ServerService.java:384)
2018-08-16 00:54:35,269 ERROR [stderr] (main) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
2018-08-16 00:54:35,269 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:748)
2018-08-16 00:54:35,333 INFO  [org.jboss.as] (MSC service thread 1-4) WFLYSRV0050: WildFly Swarm 2017.5.0 (WildFly Core 2.2.1.Final) stopped in 47ms

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.172 s
[INFO] Finished at: 2018-08-16T00:54:35-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.swarm:wildfly-swarm-plugin:2017.5.0:run (default-cli) on project admin-showcase: Process failed to start -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rmpestano** [comment]
Hi @jandrei,

The error doesn't say much to me so looks like something on your environment.

It works for me on linux and windows (3 different machines):

![showcase-swarm-windows](https://user-images.githubusercontent.com/1592273/44217175-3e9f9680-a14d-11e8-872d-dd78fb267af3.png)
![showcase-swarm-linux](https://user-images.githubusercontent.com/1592273/44217176-3e9f9680-a14d-11e8-9a91-0c56ca059466.png)
 
Does other swarm applications work for you, e.g:

https://github.com/Shynixn/Wildfly-Swarm-Samples

**Comment by jandrei** [comment]
fixed when change version of swarm to 2017.6.1 and 2017.12.1 into pom.xm.
Thank you.

![image](https://user-images.githubusercontent.com/607914/44225298-85988680-a163-11e8-876a-9686b6a83a4a.png)

I Try both examples from here https://github.com/Shynixn/Wildfly-Swarm-Samples
and they are working fine with same maven command
